# Generated by Django 5.2.4 on 2025-12-11 05:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agence', models.CharField(default='ADPME', max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('mission', models.TextField(help_text="La mission de l'agence")),
                ('vision', models.TextField(blank=True, help_text='La vision à long terme', null=True)),
                ('valeurs', models.TextField(blank=True, help_text="Les valeurs fondamentales de l'agence", null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('liens_sociaux', models.JSONField(blank=True, help_text="Ex: {'facebook':'url','linkedin':'url'}", null=True)),
                ('carte_embed_url', models.URLField(blank=True, help_text="URL d'intégration Google Maps", null=True)),
            ],
            options={
                'verbose_name': "Information de l'agence",
                'verbose_name_plural': "Informations de l'agence",
            },
        ),
        migrations.CreateModel(
            name='CategorieActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': "Catégorie d'actualité",
                'verbose_name_plural': "Catégorie d'actualités",
            },
        ),
        migrations.CreateModel(
            name='CategorieDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie de document',
                'verbose_name_plural': 'Catégories de documents',
            },
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipes/')),
                ('ordre_affichage', models.IntegerField(default=0, help_text="Ordre d'affichage sur la page de l'équipe")),
            ],
            options={
                'verbose_name': "Membre d'équipe",
                'verbose_name_plural': "Membres d'équipe",
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PageStatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(choices=[('a_propos', 'A propos'), ('document', 'Lois et textes'), ('contact', 'Contact')], max_length=100, unique=True)),
                ('contenu', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPartenanire', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires_logo/')),
                ('lien', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image_principale', models.ImageField(blank=True, help_text="Image d'illustration de l'actualité", null=True, upload_to='actualites_images/')),
                ('resume', models.TextField(blank=True, help_text='Un court résumé visible sur la liste des actualités', null=True)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('est_publie', models.BooleanField(default=True, help_text="Cochez pour publier l'actualité sur le site")),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites', to='adpme.categorieactualite')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=225)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brève description du document', null=True)),
                ('fichier', models.FileField(help_text='Le fichier à télécharger (PDF, Word, Excel, etc.)', upload_to='documents_telechargement/')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_public', models.BooleanField(default=True, help_text='Cochez pour rendre public le téléchargement')),
                ('nombre_telechargements', models.IntegerField(default=0, editable=False)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='adpme.categoriedocument')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='ImageActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Image supplémentaire pour l'actualité", upload_to='actualites_images/supplementaires/')),
                ('description', models.CharField(blank=True, help_text="Description ou légende de l'image", max_length=255, null=True)),
                ('ordre_affichage', models.IntegerField(default=0, help_text="Ordre d'affichage de l'image dans la galerie")),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autres_images', to='adpme.actualite')),
            ],
            options={
                'verbose_name': "Image d'Actualité Supplémentaire",
                'verbose_name_plural': "Images d'Actualité Supplémentaires",
                'ordering': ['ordre_affichage'],
            },
        ),
    ]
