# Generated by Django 5.2.4 on 2026-01-04 06:59

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agence', models.CharField(default='ADPME', max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('mission', models.TextField(help_text="La mission de l'agence")),
                ('vision', models.TextField(blank=True, help_text='La vision à long terme', null=True)),
                ('valeurs', models.TextField(blank=True, help_text="Les valeurs fondamentales de l'agence", null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('liens_sociaux', models.JSONField(blank=True, help_text="Ex: {'facebook':'url','linkedin':'url'}", null=True)),
                ('carte_embed_url', models.URLField(blank=True, help_text="URL d'intégration Google Maps", null=True)),
            ],
            options={
                'verbose_name': "Information de l'agence",
                'verbose_name_plural': "Informations de l'agence",
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Categorie')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualite_img', verbose_name="Image d'entête")),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('blog_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
                ('Main_post', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='adpme.category')),
            ],
            options={
                'verbose_name': 'Actualite',
                'ordering': ['-created_on'],
            },
        ),
    ]
