# Generated by Django 5.2.4 on 2026-01-03 14:35

import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agence', models.CharField(default='ADPME', max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('mission', models.TextField(help_text="La mission de l'agence")),
                ('vision', models.TextField(blank=True, help_text='La vision à long terme', null=True)),
                ('valeurs', models.TextField(blank=True, help_text="Les valeurs fondamentales de l'agence", null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('liens_sociaux', models.JSONField(blank=True, help_text="Ex: {'facebook':'url','linkedin':'url'}", null=True)),
                ('carte_embed_url', models.URLField(blank=True, help_text="URL d'intégration Google Maps", null=True)),
            ],
            options={
                'verbose_name': "Information de l'agence",
                'verbose_name_plural': "Informations de l'agence",
            },
        ),
        migrations.CreateModel(
            name='CategorieActu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': "Catégorie d'actualité",
                'verbose_name_plural': "Catégorie d'actualités",
            },
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('actu_slug', autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, populate_from='titre', unique=True)),
                ('image_principale', models.ImageField(blank=True, help_text="Image d'illustration de l'actualité", null=True, upload_to='actualites_images/')),
                ('resume', models.TextField(blank=True, help_text='Un court résumé visible sur la liste des actualités', null=True)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISH')], default='0', max_length=1)),
                ('section', models.CharField(choices=[('Recent', 'Recent'), ('Publish', 'Publish'), ('Trending', 'Trending')], default='Recent', max_length=100)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites', to='adpme.categorieactu')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='ImageActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Image supplémentaire pour l'actualité", upload_to='actualites_images/supplementaires/')),
                ('description', models.CharField(blank=True, help_text="Description ou légende de l'image", max_length=255, null=True)),
                ('ordre_affichage', models.IntegerField(default=0, help_text="Ordre d'affichage de l'image dans la galerie")),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autres_images', to='adpme.actualite')),
            ],
            options={
                'verbose_name': "Image d'Actualité Supplémentaire",
                'verbose_name_plural': "Images d'Actualité Supplémentaires",
                'ordering': ['ordre_affichage'],
            },
        ),
    ]
