# Generated by Django 5.2.4 on 2026-01-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogactualite',
            name='section',
            field=models.CharField(choices=[('Recent', 'Recent'), ('Publish', 'Publish'), ('Trending', 'Trending')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogactualite',
            name='status',
            field=models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISH')], default='0', max_length=1),
        ),
    ]
