# Generated by Django 5.2.4 on 2026-01-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adpme', '0002_blogactualite_section_blogactualite_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
    ]
