# Generated by Django 5.2.4 on 2026-01-04 14:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adpme', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogactualite',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
