# Generated by Django 5.2.4 on 2026-01-20 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpme', '0004_alter_blogactualite_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualiteEnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='actualite_galerie/')),
                ('caption', models.CharField(blank=True, help_text="Description facultative de l'image", max_length=255)),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie', to='adpme.blogactualite')),
            ],
        ),
    ]
