# Generated by Django 5.2.4 on 2026-01-31 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpme', '0005_actualiteenimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogactualite',
            options={'ordering': ['-date_publication'], 'verbose_name': 'Actualite'},
        ),
        migrations.AddField(
            model_name='blogactualite',
            name='date_publication',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de publication effective'),
        ),
    ]
